version: '3'
services:
    nginx:
        build:
            dockerfile: ./dockefile/nginx.dockefile
            context: .
        image: flavio/nginx
        container_name: nginx
        ports:
            - "80:80"
        networks:
            - production-network
        depends_on:
            - "node1"
            - "node2"
            - "node3"
    
    mongodb:
        image: mongo
        networks:
            - production-network
            
    node1:
        build:
            dockefile: ./dockefile/node.dockefile
            context: .
        image: flavio/node
        container_name: node-1
        ports:
            - "3000"
        networks:
            - production-network
        depends_on:
            - "mongodb"
            
    node2:
        build:
            dockefile: ./dockefile/node.dockefile
            context: .
        image: flavio/node
        container_name: node-2
        ports:
            - "3000"
        networks:
            - production-network
        depends_on:
            - "mongodb"
         
    node3:
        build:
            dockefile: ./dockefile/node.dockefile
            context: .
        image: flavio/node
        container_name: node-3
        ports:
            - "3000"
        networks:
            - production-network
        depends_on:
            - "mongodb"
            
    networks:
        production-network:
            driver: bridge
            